#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't push directly to master branch"
  exit 1
fi
cd client
npm run prettify && npm run lint
